### ISSUE TITLE
Adding a Rank column

### ISSUE THREAD

**Issue by jocisco** [sficarrotta/WSJF_V3#2]
Thanks you for this great example.
Could you help me figure out how to add a "Rank" column and ideally allow rows to be reordered?

**Comment by sficarrotta** [comment]
Greetings,

I'm looking into adding "Rank" and allowing re-ordering. I've run into a
glitch, but hopefully will have an update soon.

Summer

On Thu, Jan 8, 2015 at 11:22 PM, jocisco <notifications@github.com> wrote:

> Thanks you for this great example.
> Could you help me figure out how to add a "Rank" column and ideally allow
> rows to be reordered?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sficarrotta/WSJF_V3/issues/2>.
>



-- 

*Summer Ficarrotta** Technical Account Manager**, Rally Software*
Tel: (719) 964-2317
www.rallydev.com


Get New Teams Up and Running Quickly with Rally TeamStart Live complementary
Webinars every Tuesday.  http://forms.rallydev.com/teamstartregistration

Join the conversation in the Rally Success Community
<https://success.rallydev.com>.

<http://www.scrumalliance.org/pages/CSM>
<http://www.linkedin.com/in/sficarrotta>

**Comment by jocisco** [comment]
Yeah, I've tried I couldn't get it to work either. Thanks.

**Comment by sficarrotta** [comment]
The most recent version of this app is here: https://github.com/RallyCommunity/WSJF_Grid
Bug fixes, some improved release filtering
